language: go

go:
  - 1.13.x

env:
  global:
    - GO111MODULE=on

script:
  - make ci
  - go mod tidy

after_success:
  - git status

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash -s -- --rm-dist
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux

cache:
  directories:
    - $HOME/gopath/pkg/mod
