language: go

go:
  - 1.12.x

env:
  global:
    - GO111MODULE=on

script:
  - make ci

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash -s -- --rm-dist
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
